---
- name: Add InfluxData GPG key
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive.key
    state: present

- name: Add InfluxData APT repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian stable main"
    state: present

- name: Ensure APT cache is updated
  apt:
    update_cache: yes

- name: Install influxdb2
  apt:
    name: "influxdb2"
    update_cache: yes
    state: present

- name: Enable and start influxdb2
  systemd:
    name: influxdb2
    enabled: yes
    state: started
